// Racing Terms glossary used by the hover tooltips (generated from terms.html)
window.RM_TERMS = {
 "IMSA": "Stands for International Motor Sports Association. It is the governing body and championship series for sports car racing in North America.",
 "Formula 1 (F1)": "The FIA Formula 1 World Championship is the pinnacle of single-seater racing and the most prestigious motorsport series in the world. F1 cars are purpose-built, open-wheel racing machines representing the absolute cutting edge of automotive technology.",
 "IndyCar": "The NTT IndyCar Series is North America's top single-seater championship. All teams use the same Dallara chassis with either a Chevrolet or Honda engine, so driver skill and team strategy decide races.",
 "FIA WEC": "The FIA World Endurance Championship — the global version of IMSA. Run by the FIA (the worldwide governing body of motorsport), WEC races across multiple continents with Le Mans as its centrepiece event.",
 "BPR Global GT Series": "A privately-organised racing series founded in 1994 by Barth, Peter and Ratel (the B, P and R). It gave GT supercars a proper international championship to race in before the FIA took over and renamed it the FIA GT Championship in 1997.",
 "Grand Prix": "French for \"Grand Prize\" — the name given to each individual F1 race. Each Grand Prix is named after its host country or region (e.",
 "Pole Position": "The first starting position on the grid, awarded to the driver who sets the fastest qualifying lap time. Starting from pole gives a significant advantage as the driver leads into the first corner with clear track ahead.",
 "DRS (Drag Reduction System)": "A moveable rear wing flap that reduced drag to give extra speed on straights. From 2011 to 2025, drivers could open it in set zones when within one second of the car ahead, to help overtaking.",
 "Qualifying": "A time-trial session held before the race to determine the starting grid order. Qualifying is split into three knockout rounds (Q1, Q2, Q3), with the slowest drivers eliminated after each round.",
 "Constructor": "The team/manufacturer that builds the F1 car — examples include Mercedes, Ferrari, Red Bull Racing, McLaren. The Constructors' Championship is awarded to the team that scores the most combined points from both of its drivers across a season.",
 "Parc Ferme": "French for \"closed park\" — a strict set of regulations that prevents teams from making significant changes to their cars between qualifying and the race. Once a car enters parc fermé (after qualifying), only minor adjustments are allowed.",
 "Power Unit": "Modern F1's term for the complete propulsion system — a 1.6-litre turbocharged V6 combined with electric motor-generators that harvest and deploy energy.",
 "Undercut / Overcut": "Pit stop strategies used to gain track position. An undercut means pitting earlier than your rival to gain an advantage with fresh tyres on clear track.",
 "Indianapolis 500": "The 500-mile race (200 laps) held every May at the Indianapolis Motor Speedway since 1911. Known as \"The Greatest Spectacle in Racing\", it draws more than 300,000 spectators and is part of motorsport's Triple Crown.",
 "Oval Racing": "Racing on a closed loop of banked left-hand turns, like Indianapolis or Texas. Speeds are extremely high (over 370 km/h at Indy) and cars run nose-to-tail in each other's slipstream for lap after lap.",
 "Push-to-Pass": "A button that gives a temporary power boost (around 60 extra horsepower) on road and street courses. Each driver gets a fixed number of seconds to use across the whole race, so they must choose between attacking, defending or saving it for the final laps.",
 "Aeroscreen": "A ballistic screen that wraps around the cockpit, introduced in 2020. It combines a titanium frame (similar to F1's Halo) with a toughened polycarbonate windscreen that protects the driver's head from debris.",
 "Rolling Start": "Unlike F1's standing starts, IndyCar races usually begin with the field already moving behind the pace car. When the pace car pulls into the pits, the leader controls the pace until the green flag waves.",
 "Full-Course Caution": "When there is a crash or debris, IndyCar brings out the yellow flag for the whole track and sends out a pace car. The field bunches up behind it and the pit lane usually closes at first.",
 "Bump Day": "The Indy 500 has just 33 starting spots. When more cars enter than that, the slowest qualifiers are \"bumped\" out of the race in a tense shootout now called Last Chance Qualifying.",
 "Drinking the Milk": "The Indy 500 winner celebrates by drinking a bottle of milk in Victory Lane instead of spraying champagne. It began when Louis Meyer drank buttermilk after winning in 1936, and it became an official tradition in 1956.",
 "Triple Crown of Motorsport": "The unofficial title for winning the Monaco Grand Prix, the Indianapolis 500 and the 24 Hours of Le Mans during a career. Only Graham Hill has ever achieved it.",
 "GT1 Class": "The top class of GT racing in the late 1990s. Cars had to be based on a road-going production vehicle but are heavily modified for racing.",
 "GTP Class": "Grand Touring Prototype — IMSA's top class through the 1980s and early 90s. Unlike GT classes, GTP cars were purpose-built racing prototypes not derived from road cars.",
 "LMP1 / LMP2": "Le Mans Prototype classes. LMP1 was the absolute top class — the fastest, most technologically advanced racing cars in the world during the hybrid era (Audi R18, Porsche 919, Toyota TS050).",
 "Hypercar Class": "The top class in WEC since 2021, replacing LMP1. Designed to bring more manufacturers back to the top of endurance racing with lower costs and Balance of Performance.",
 "GT3 Class": "The customer racing class introduced in 2006. GT3 cars are production-based supercars (Porsche 911, Ferrari 488, Audi R8, Mercedes-AMG GT3) modified for racing and sold to private teams.",
 "GT4 Class": "A more affordable customer racing class below GT3, introduced in 2007. GT4 cars have less power (around 400hp) and fewer modifications than GT3, making them perfect for amateur racers and developing drivers.",
 "Balance of Performance (BoP)": "The equalization system that keeps all GT3 manufacturers competitive. Race organizers adjust each car's weight, engine power, fuel capacity, and aerodynamics to ensure no single manufacturer has an unfair advantage.",
 "Pro-Am / Silver Cup": "A driver category system in GT3 racing. Professional factory drivers are rated Platinum or Gold.",
 "Gentleman Driver": "A wealthy amateur racer who purchases a GT3 car and hires professional drivers as teammates. Gentleman drivers fund their own racing programs and compete in Pro-Am classes.",
 "24h Series / GT World Challenge": "The major GT3 championship series worldwide. The GT World Challenge (formerly Blancpain GT Series) crowns European, Asian, and American champions.",
 "Sprint Race": "A short-distance race typically lasting 60-90 minutes, where outright speed matters more than tyre management or fuel strategy. F1 races are sprint format — drivers push flat-out for the entire duration.",
 "Endurance Racing": "Races measured in hours rather than laps. The winner is the car that covers the most distance within the time limit.",
 "Multi-Class Racing": "When different categories of cars race simultaneously on the same track. At Le Mans, LMP1 prototypes, LMP2 prototypes and GT cars all race at the same time.",
 "Downforce": "Aerodynamic force that pushes the car downward onto the track, generated by wings, splitters and the car's underbody. More downforce = more grip through corners = faster cornering speeds.",
 "Homologation": "The official approval process that makes a racing car legal to compete. For GT1, a manufacturer had to build a minimum number of road-going versions of the car before the race version was approved.",
 "Hybrid Power": "A system where a car uses both a traditional combustion engine and an electric motor. In LMP1 racing, cars like the Porsche 919 and Toyota TS050 used hybrid systems that recovered energy under braking and deployed it as extra power out of corners.",
 "Monaco": "The Monaco Grand Prix — F1's most prestigious and glamorous race, held on the tight, narrow streets of Monte Carlo. Overtaking is nearly impossible, making qualifying crucial.",
 "Spa-Francorchamps": "The legendary Circuit de Spa-Francorchamps in Belgium — one of the most challenging and revered tracks in motorsport. Famous for Eau Rouge, a high-speed uphill corner that tests driver bravery.",
 "La Sarthe": "The official name of the Le Mans circuit — Circuit de la Sarthe is named after the Sarthe departement (region) in northwest France where it's located.",
 "The Brickyard": "The nickname of the Indianapolis Motor Speedway. In 1909 the original track was paved with 3.",
 "Purple Sector": "A purple sector time means that lap segment is the fastest anyone has set all session — the absolute best time across every driver. You'll see it on timing screens and TV overlays.",
 "Red Sector": "A red sector means the lap or sector time has been invalidated — most commonly because the driver exceeded track limits by going beyond the white lines at a corner.",
 "Green Sector": "A green sector means the driver has beaten their own personal best time through that section of the lap.",
 "Yellow Sector": "A yellow sector means the driver's time through that part of the lap is slower than their own personal best for that sector.",
 "🏁 Chequered Flag": "The most iconic flag in motorsport. Waved at the finish line to signal the end of a race, qualifying session, or practice.",
 "🟡 Yellow Flag": "Signals danger ahead — usually a stopped car, debris, or an incident on track. Drivers must slow down and are strictly forbidden from overtaking under yellow.",
 "🔴 Red Flag": "The session is stopped immediately. All drivers must slow down and return to the pit lane.",
 "🔵 Blue Flag": "Shown to a driver about to be lapped by a faster car. It's a warning to let the leading car past without impeding it.",
 "🟢 Green Flag": "Signals that the track is clear and racing can resume — typically shown after a yellow flag period, safety car, or at the start of a session. When drivers see the green flag, full racing speed and overtaking are permitted again.",
 "🟠 Orange Flag (Meatball)": "Also known as the meatball flag — a black flag with an orange disc in the centre. It's shown alongside a car number to tell that specific driver they have a mechanical problem and must pit immediately for repairs.",
 "⬛ Black Flag": "The most severe flag shown to an individual driver — it means disqualification. Shown alongside the car number, it orders that driver to return to the pits immediately and retire from the race.",
 "⬜ White Flag": "The white flag has two different meanings depending on the series. In Formula 1, it warns drivers that a slow-moving staff or medical vehicle is on track — drivers must be alert and prepared to avoid it.",
 "NASCAR": "The National Association for Stock Car Auto Racing, founded in 1948. Its top division, the Cup Series, races heavy, powerful \"stock cars\" mostly on oval tracks, and it is the most-watched form of motorsport in the United States.",
 "Super GT": "Japan's top grand touring championship, founded in 1993 as the JGTC. Two classes race together: GT500 factory cars from Toyota, Nissan and Honda, and the large GT300 class for GT3 and Japanese-built cars.",
 "DTM": "The Deutsche Tourenwagen Masters, Germany's famous touring car series. It began in 1984 with modified production cars, later raced its own high-tech silhouette cars, and has used GT3 cars since 2021.",
 "Superspeedway": "An oval track two miles or longer, like Daytona and Talladega. Cars run flat out in huge packs, and NASCAR limits engine power there for safety, first with restrictor plates from 1988 and later with tapered spacers.",
 "Drafting": "Driving right behind another car to use its slipstream. Two cars nose-to-tail are faster than one alone, so drivers team up in lines, then try to slingshot past at the end.",
 "The Big One": "The nickname for the huge multi-car crash that often happens at Daytona and Talladega. With 40 cars running inches apart at around 200 mph, one small mistake can collect a dozen cars or more.",
 "Stage Racing": "Since 2017, most Cup races are split into three stages. The top ten at the end of the first two stages earn bonus points, which rewards drivers for racing hard all day, not only at the finish.",
 "GT500 / GT300": "Super GT's two classes. GT500 is the top class of factory-built cars with about 600+ horsepower.",
 "Success Ballast": "Extra weight added to cars that score points, to stop one team from running away with the title. The more you score, the heavier your car becomes, until the ballast is removed for the final round.",
 "Class One": "A set of shared technical rules created by the DTM and Super GT so their cars could race each other. It used 2.",
 "Touring Car": "A racing car based on a road-going saloon or coupé, like the Mercedes 190E or Alfa Romeo 155. Touring car racing is famous for close, contact-heavy battles because the cars look like what fans drive every day."
};
